name: git_repo_watcher
description: Flutter project.
publish_to: 'none'
version: 1.4.3

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  http: ^1.4.0
  fluttertoast: ^8.2.12
  easy_dynamic_theme: ^2.3.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  dynamic_value: ^3.0.0
  jiffy: ^6.4.3
  cupertino_icons: ^1.0.2
  dynamic_system_colors: ^1.8.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/